
SELECT		*
FROM		PRODUTOS


UPDATE		[PRODUTOS]
SET			 [PREÇO LISTA] = 5
			,[SABOR] = 'Laranja'
			,[EMBALAGEM] = 'PET'
WHERE		[CÓDIGO] = '1040107'

-- Alterando em 10 % o preço atual dos refrigerantes de sabor maracujá

UPDATE		PRODUTOS
SET			[PREÇO LISTA] = [PREÇO LISTA] * 1.10
FROM		PRODUTOS
WHERE		SABOR = 'Maracujá'

SELECT		*
FROM		PRODUTOS
WHERE		SABOR = 'Maracujá'

-- Alterando dados de um cliente

SELECT		*
FROM		CLIENTES
WHERE		[CPF] = '19290992743'

UPDATE		CLIENTES
SET			 [ENDEREÇO] = 'R. Jorge Emilio 23'
			,BAIRRO = 'Santo Amaro'
			,CIDADE = 'São Paulo'
			,ESTADO = 'SP'
			,CEP	= '8833223'
WHERE		CPF		= '19290992743'

-- UPDATE com FROM

SELECT		*
FROM		[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]
WHERE		[CODIGO DO PRODUTO] = '1000889'

SELECT		*
FROM		PRODUTOS
WHERE		[CÓDIGO] = '1000889'

UPDATE		[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]
SET			[PREÇO DE LISTA] = 7
WHERE		[CODIGO DO PRODUTO] = '1000889'

-- Alterando a partir de outro banco

SELECT		B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CÓDIGO], A.[PREÇO LISTA]
FROM		[PRODUTOS] A
INNER JOIN	[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON			B.[CODIGO DO PRODUTO] = A.[CÓDIGO]
WHERE		A.[CÓDIGO] = '1000889'

UPDATE		A
SET			A.[PREÇO LISTA] = B.[PREÇO DE LISTA]
FROM		[PRODUTOS] A
INNER JOIN	[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON			A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
WHERE		A.[CÓDIGO] = '1000889'

-- Alterando volume de compras

SELECT		*
FROM		CLIENTES

UPDATE		A
SET			A.[VOLUME COMPRA] = A.[VOLUME COMPRA] * 1.30 
FROM		CLIENTES A
INNER JOIN	VENDEDORES B
ON			A.BAIRRO = B.BAIRRO

-- Usando MERGE para alterar dados

SELECT		*
FROM		[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]
WHERE		[CODIGO DO PRODUTO] = '1002334'

SELECT		*
FROM		PRODUTOS
WHERE		[CÓDIGO] = '1002334'

SELECT		B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CÓDIGO], A.[PREÇO LISTA]
FROM		[PRODUTOS] A
INNER JOIN	[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON			A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
WHERE		[CÓDIGO] = '1002334'

MERGE INTO		PRODUTOS A
USING			[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON				A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
AND				[CÓDIGO] = '1002334'
WHEN MATCHED	
THEN
UPDATE
SET				A.[PREÇO LISTA] = B.[PREÇO DE LISTA];

-- Alterando em 30 %

MERGE INTO		CLIENTES A
USING			VENDEDORES B
ON				A.BAIRRO = B.BAIRRO
WHEN MATCHED	
THEN
UPDATE
SET				A.[VOLUME COMPRA] = A.[VOLUME COMPRA] * 1.30;