WHERE = (Condição de busca, ONDE)
UPDATE = Alterar
SET = (Pegar) [EMBALAGEM] (E inserir) = 'Lata'

UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'Lata',
	[PRECO DE LISTA] = 2.46
WHERE [CODIGO PRODUTO] = '544931'

UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1078680'