
SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(decimal(10,5), 193.57)

SELECT * FROM [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  [PREÇO DE LISTA] 
from [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  CONVERT(VARCHAR, [PREÇO DE LISTA]) 
from [TABELA DE PRODUTOS]

-- Concatenar cliente, faturamento e ano

SELECT		*
FROM		[ITENS NOTAS FISCAIS]

SELECT		*
FROM		[NOTAS FISCAIS]

SELECT		CPF, SUM(QUANTIDADE * PREÇO) TOTAL
FROM		[ITENS NOTAS FISCAIS] INF
INNER JOIN	[NOTAS FISCAIS] NF
ON			INF.NUMERO = NF.NUMERO
WHERE		YEAR(DATA) = 2016
GROUP BY	CPF

SELECT		CONCAT('O cliente ', TBC.NOME, ' faturou '
			,CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), SUM(QUANTIDADE * PREÇO)))
			,' no ano de '
			,CONVERT(VARCHAR, YEAR(DATA))) AS SETENÇA
FROM		[ITENS NOTAS FISCAIS] INF
INNER JOIN	[NOTAS FISCAIS] NF
ON			INF.NUMERO = NF.NUMERO
INNER JOIN	[TABELA DE CLIENTES] TBC
ON			TBC.CPF = NF.CPF
WHERE		YEAR(DATA) = 2016
GROUP BY	TBC.NOME, YEAR(DATA)

