CREATE TABLE [TABELA DE CLIENTES]
(
[CPF] [VARCHAR] (11),
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERECO2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [VARCHAR] (2),
[CEP] [VARCHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [VARCHAR] (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT]
)

CREATE TABLE [TABELA DE VENDEDORES]
( 
[MATRICULA] [VARCHAR] (5),
[NOME] [VARCHAR] (100),
[PERCENTUAL DE COMISSAO] [FLOAT]
)
