-- Definindo padrões para os campos

CREATE	TABLE	TAB_PADRAO
(
ID INT IDENTITY(1,1) NOT NULL,
DESCRITOR VARCHAR(20) NULL,
ENDEREÇO VARCHAR(200) NULL,
CIDADE VARCHAR(50) DEFAULT 'Cidade não definida',
DATA_CRIAÇÃO DATE DEFAULT GETDATE()
)

INSERT INTO TAB_PADRAO
(DESCRITOR)
VALUES
(
'CLIENTE Y'
)

SELECT	*
FROM	TAB_PADRAO

-- Usando CHECK para testar campos

CREATE TABLE	TAB_CHECK
(
 ID		INT	NOT NULL
,NOME	VARCHAR(20) NULL
,IDADE	INT NULL
,CIDADE	VARCHAR(20)	NULL
,CONSTRAINT CHK_PESSOA
 CHECK		(IDADE >= 18)
)

-- TRIGGER

-- Armazenando o faturamento a cada inserção, atualização e deleção na tabela

CREATE TABLE	TAB_FATURAMENTO
(
DATA_VENDA		DATE	NULL,
TOTAL_VENDA		FLOAT
)

CREATE TRIGGER		TG_ITENS_VENDIDOS
ON					[ITENS VENDIDOS]
AFTER				 INSERT
					,UPDATE
					,DELETE
AS
BEGIN
DELETE FROM			TAB_FATURAMENTO;
INSERT INTO			TAB_FATURAMENTO
					(
					DATA_VENDA
					,TOTAL_VENDA
					)
SELECT				A.[DATA] AS DATA_VENDA, SUM(B.[QUANTIDADE] * B.[PREÇO]) TOTAL_VENDA
FROM				[NOTAS] A
INNER JOIN			[ITENS VENDIDOS] B
ON					A.NÚMERO = B.NÚMERO
GROUP BY			A.[DATA];
END;


INSERT INTO		NOTAS 
				(
				[NÚMERO], [DATA],[CPF],[MATRÍCULA],[IMPOSTO]
				)
VALUES			
				(
				'0100'
				,'2018-05-15'
				,'1471156710'
				,'235'
				,0.18
				)


INSERT INTO		[ITENS VENDIDOS]
				(
				[NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO]
				)
VALUES
				(
				'0100'
				,'1000889'
				,'100'
				,1
				)


				INSERT INTO		[ITENS VENDIDOS]
				(
				[NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO]
				)
VALUES
				(
				'0100'
				,'1002334'
				,'100'
				,1
				)

	SELECT		*
	FROM		TAB_FATURAMENTO


DELETE
FROM		[ITENS VENDIDOS]
WHERE		NÚMERO = '0102'
AND			CÓDIGO = '1002334'

UPDATE		[ITENS VENDIDOS]
SET			QUANTIDADE = 300
WHERE		NÚMERO = '0102'
AND			CÓDIGO = '1000889'

-- Alterando idade do cliente com data atual

SELECT		[CPF], [IDADE], [DATA NASCIMENTO],
DATEDIFF	(
			YEAR, [DATA NASCIMENTO], GETDATE()
			)
FROM		CLIENTES

CREATE TRIGGER		TG_CLIENTES_IDADE
ON					CLIENTES
AFTER				 INSERT
					,UPDATE
					,DELETE
AS
BEGIN
UPDATE				CLIENTES
SET					[IDADE] = 
					(
					DATEDIFF
					(
					YEAR, [DATA NASCIMENTO], GETDATE()
					)
					)
END;

UPDATE			CLIENTES
SET				[DATA NASCIMENTO] = '2002-09-01'
WHERE			[CPF] = '1471156710'
