/* Filtrando por datas */

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	[DATA DE NASCIMENTO] = '1995-09-11'

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	[DATA DE NASCIMENTO] >= '1995-09-11'

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	[DATA DE NASCIMENTO] > '1995-09-11'

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	[DATA DE NASCIMENTO] <= '1995-09-11'

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	[DATA DE NASCIMENTO] < '1995-09-11'

/* Filtrar todo mundo que nasceu em 1995 */

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	YEAR ([DATA DE NASCIMENTO]) = 1995

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	YEAR ([DATA DE NASCIMENTO]) > 1995

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	YEAR ([DATA DE NASCIMENTO]) < 1995

/* Filtrar todo mundo que nasceu em setembro (09) */

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	MONTH ([DATA DE NASCIMENTO]) = 09

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	MONTH ([DATA DE NASCIMENTO]) > 09

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	MONTH ([DATA DE NASCIMENTO]) < 09

/* Filtrar todo mundo que nasceu no dia (01) */

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	DAY ([DATA DE NASCIMENTO]) = 11

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	DAY ([DATA DE NASCIMENTO]) > 11

SELECT	*
FROM	[TABELA DE CLIENTES]
WHERE	DAY ([DATA DE NASCIMENTO]) < 11