SELECT		*
FROM		[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]

INSERT INTO		[PRODUTOS]
(
				[CÓDIGO], [DESCRITOR], [SABOR], [TAMANHO], [EMBALAGEM], [PREÇO LISTA]
)
SELECT			[CODIGO DO PRODUTO] AS CÓDIGO, [NOME DO PRODUTO] AS DESCRITOR, [SABOR], [TAMANHO], [EMBALAGEM], [PREÇO DE LISTA] AS [PREÇO LISTA]
FROM			[SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]
WHERE			[CODIGO DO PRODUTO] <> '1040107'

INSERT INTO		[CLIENTES]
(
[CPF], [NOME], [ENDEREÇO], [BAIRRO], [CIDADE], [ESTADO], [CEP], [DATA NASCIMENTO], [IDADE], [SEXO], [LIMITE CRÉDITO], [VOLUME COMPRA], [PRIMEIRA COMPRA]
)
SELECT		[CPF], [NOME]
			, [ENDERECO 1] AS ENDEREÇO, [BAIRRO], [CIDADE], [ESTADO], [CEP]
			, [DATA DE NASCIMENTO] AS [DATA NASCIMENTO]
			, [IDADE], [SEXO], [LIMITE DE CREDITO] AS [LIMITE CRÉDITO]
			, [VOLUME DE COMPRA] AS [VOLUME COMPRA]
			, [PRIMEIRA COMPRA]
FROM		[SUCOS_VENDAS].[DBO].[TABELA DE CLIENTES]
WHERE		[CPF] NOT IN ('1471156710', '19290992743', '2600586709')
