
-- Testar quanto cada cliente comprou dentro de um mês, pegar o valor e comparar com o valor que ta no cadastro
-- Se o valor for maior do que o valor do cadastro, a venda foi invalida, se for menor a venda ta valida

SELECT		AUX1.NOME, AUX1.ANO_MES, AUX1.QUANTIDADE_MES, AUX1.[VOLUME DE COMPRA], CONVERT(DECIMAL(10,2),((AUX1.QUANTIDADE_MES/AUX1.[VOLUME DE COMPRA]) -1) * 100),
			CASE
				WHEN	QUANTIDADE_MES > [VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA'
			END AS STATUS_VENDA
FROM
(
SELECT		TBC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TBC.[VOLUME DE COMPRA]
FROM
(
SELECT		NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES
FROM		[NOTAS FISCAIS] NF
INNER JOIN	[ITENS NOTAS FISCAIS] INF
ON			NF.NUMERO = INF.NUMERO 
GROUP BY	NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7)
) CQ
INNER JOIN	[TABELA DE CLIENTES] TBC
ON			CQ.CPF = TBC.CPF
) AUX1
ORDER BY	AUX1.NOME, AUX1.ANO_MES














