SELECT		*
FROM		[TABELA DE PRODUTOS]

SELECT		*
FROM		[ITENS NOTAS FISCAIS]

SELECT		*
FROM		[NOTAS FISCAIS]

SELECT		SABOR, FATURAMENTO_2016.ANO
			,CONVERT(DECIMAL(15,2), FATURAMENTO_2016.FATURAMENTO) FATURAMENTO
			,CONVERT(VARCHAR, CONVERT(DECIMAL(10,2), (FATURAMENTO_2016.FATURAMENTO / FATURAMENTO_TOTAL.FATURAMENTO_TOTAL) * 100)) + ' %'  PARTICIPACAO
FROM
(
SELECT		YEAR(NF.DATA) ANO,	(SUM(INF.QUANTIDADE * INF.PREÇO)) FATURAMENTO_TOTAL
FROM		[TABELA DE PRODUTOS] TP
INNER JOIN	[ITENS NOTAS FISCAIS] INF
ON			TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN	[NOTAS FISCAIS] NF
ON			NF.NUMERO = INF.NUMERO
WHERE		YEAR(NF.DATA) = 2016
GROUP BY	YEAR(NF.DATA)
) FATURAMENTO_TOTAL
INNER JOIN
(
SELECT		SABOR, YEAR(NF.DATA) ANO, CONVERT(DECIMAL(15,2), (SUM(INF.QUANTIDADE * INF.PREÇO))) FATURAMENTO
FROM		[TABELA DE PRODUTOS] TP
INNER JOIN	[ITENS NOTAS FISCAIS] INF
ON			TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN	[NOTAS FISCAIS] NF
ON			NF.NUMERO = INF.NUMERO
WHERE		YEAR(NF.DATA) = 2016
GROUP BY	SABOR, YEAR(NF.DATA)
) FATURAMENTO_2016
ON			FATURAMENTO_TOTAL.ANO = FATURAMENTO_2016.ANO
GROUP BY	SABOR, FATURAMENTO_2016.ANO, FATURAMENTO_2016.FATURAMENTO, FATURAMENTO_TOTAL
ORDER BY	FATURAMENTO DESC