CREATE TABLE			[ITENS VENDIDOS]
(
 [NÚMERO]					VARCHAR (5) NOT NULL
,[CÓDIGO]					VARCHAR (10) NOT NULL
,[QUANTIDADE]				INT
,[PREÇO]					FLOAT
,CONSTRAINT					PK_ITENS_VENDIDOS
 PRIMARY KEY CLUSTERED		([NÚMERO], [CÓDIGO])
)

ALTER TABLE					[ITENS VENDIDOS]
WITH CHECK ADD CONSTRAINT	[FK_ITENS_VENDIDOS_NOTAS]
FOREIGN KEY					([NÚMERO])
REFERENCES					[NOTAS] ([NÚMERO])

ALTER TABLE					[ITENS VENDIDOS]
WITH CHECK ADD CONSTRAINT	[FK_ITENS_VENDIDOS_PRODUTOS]
FOREIGN KEY					([CÓDIGO])
REFERENCES					[PRODUTOS] ([CÓDIGO])