-- Definição de cursor
/*

Cursos é uma estrutura implementada no T-SQL que permite uma interatividade
linha a linha através de uma determinada ordem.

Frases para uso do Cursor:

. Declaração - Onde definimos qual consulta SQL estará sendo carregada ao Cursor;
. Abertura: Abrimos o cursor para percorrê-lo linha a linha;
. Posiciona na primeira linha do Cursor;
. Percorre linha a linha até o seu final;
. Fecha o Cursor;
. Limpa o Cursor da memória.

*/ 

-- Exemplo cursor

DECLARE	@NOME	VARCHAR(200)
DECLARE	CURSOR1	CURSOR FOR 
SELECT TOP 4	NOME
FROM			[TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME
WHILE @@FETCH_STATUS	=	0
BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR1 INTO @NOME
END

-- Achando o valor total do crédito

DECLARE	@LIMITECREDITO_TOTAL	INT
DECLARE	LIMITECRED_CURSOR	CURSOR FOR
SELECT	SUM([LIMITE DE CREDITO])
FROM	[TABELA DE CLIENTES]
OPEN	LIMITECRED_CURSOR
FETCH NEXT FROM	LIMITECRED_CURSOR INTO @LIMITECREDITO_TOTAL
WHILE	@@FETCH_STATUS = 0
BEGIN
	PRINT @LIMITECREDITO_TOTAL
	FETCH NEXT FROM	LIMITECRED_CURSOR INTO @LIMITECREDITO_TOTAL
END

-- Acessando mais de um campo com Cursor

DECLARE	@NOME		VARCHAR(200)
DECLARE	@ENDERECO	VARCHAR(MAX)
DECLARE	CURSORCAMPO CURSOR	FOR
SELECT	NOME, ([ENDERECO 1] + ' - ' + BAIRRO  + ' - '  + CIDADE  + ' - ' + ESTADO  + ' - ' + CEP) ENDCOMPLETO
FROM	[TABELA DE CLIENTES]
OPEN	CURSORCAMPO
FETCH NEXT FROM CURSORCAMPO
INTO			@NOME, @ENDERECO
WHILE			@@FETCH_STATUS = 0
BEGIN
	PRINT			@NOME + ' Endereço: ' + @ENDERECO
	FETCH NEXT FROM	CURSORCAMPO
	INTO			@NOME, @ENDERECO
END

-- Calculando valor total do faturamento com mais de um campo

DECLARE	@QUANTIDADE	INT
DECLARE	@PRECO		FLOAT
DECLARE	@FATURAMENTOACUM FLOAT
SET		@FATURAMENTOACUM = 0
DECLARE	CURSORFATURAMENTO CURSOR FOR
SELECT		INF.QUANTIDADE, INF.PREÇO
FROM		[NOTAS FISCAIS] NF
INNER JOIN	[ITENS NOTAS FISCAIS] INF
ON			INF.NUMERO = NF.NUMERO
WHERE		MONTH(NF.[DATA]) = 1
AND			YEAR(NF.[DATA]) = 2017
OPEN	CURSORFATURAMENTO
FETCH NEXT FROM		CURSORFATURAMENTO
INTO				@QUANTIDADE, @PRECO
WHILE	@@FETCH_STATUS = 0
BEGIN
	SET			@FATURAMENTOACUM = @FATURAMENTOACUM + (@QUANTIDADE * @PRECO)
	FETCH NEXT FROM	CURSORFATURAMENTO
	INTO			@QUANTIDADE, @PRECO
END
CLOSE		CURSORFATURAMENTO
DEALLOCATE	CURSORFATURAMENTO
PRINT		@FATURAMENTOACUM
