
-- Declaração de variáveis

DECLARE @IDADE	INT
DECLARE	@NOME	VARCHAR(200)
DECLARE	@DATA	DATE

-- Declarando em conjunto

DECLARE	
 @IDADE2	INT
,@NOME2		VARCHAR(200)
,@DATA2		DATE

-- Dando valores às variáveis

SET		@IDADE	=	20
-- PRINT	@IDADE

SET		@NOME	=	'João da Silva'
-- PRINT	@NOME

SET		@DATA	=	'20221005'
-- PRINT	@DATA

-- Declarar variáveis e usar o comando SELECT para atribuir os valores

DECLARE	@CPF	VARCHAR(12)
SET		@CPF	= '2600586709'

/* SELECT	NOME,[DATA DE NASCIMENTO], IDADE
FROM	[TABELA DE CLIENTES]
WHERE	CPF	=	@CPF */

SELECT	@NOME2 = NOME, @DATA2 = [DATA DE NASCIMENTO], @IDADE2 = IDADE
FROM	[TABELA DE CLIENTES]
WHERE	CPF	=	@CPF

PRINT	@NOME2
PRINT	@DATA2
PRINT	@IDADE2

-- Introduzindo novo vendedor com variáveis

/*

DECLARE
 @MATRICULA	VARCHAR(5)
,@NOME		VARCHAR(100)
,@PERCENTUAL	FLOAT
,@DATA		DATE
,@FERIAS		BIT
,@BAIRRO		VARCHAR(100)

SET @MATRICULA	=	'00239'
SET	@NOME		=	'José Mattos'
SET	@PERCENTUAL	=	0.10
SET	@DATA		=	'20100120'
SET	@FERIAS		=	1
SET	@BAIRRO		=	'Meier'

INSERT	INTO	[TABELA DE VENDEDORES]
(
MATRICULA,NOME,[PERCENTUAL COMISSÃO],[DATA ADMISSÃO],BAIRRO,[DE FERIAS]
)
VALUES
(
@MATRICULA,@NOME,@PERCENTUAL,@DATA,@BAIRRO,@FERIAS
)

*/