
-- Tratamento de ERRO --

/*
Temos duas formas de tratar erros no T-SQL:

. Não usando a estrutura TRY-CATCH
. Usando a estrutura TRY-CATCH

TRY
	<BLOCO DE COMANDOS>
CATCH
	<BLOCO DE COMANDOS CASO HAJA ERRO>
END TRY

No caso de não usar o TRY-CATCH temos duas funções que devemos usar:

@@ERROR = Retorna um inteiro que representa a forma com que o comando anterior
terminou.
(Zero indica que executou com sucesso, diferente de zero houve um erro)

@@ROWCOUNT = Número de linhas afetadas com o erro.

A obtenção destes dados devem ser feitas após o comando suspeito do erro

*/

DECLARE		@DENOMINADOR INT
SET			@DENOMINADOR = 0
SELECT		SUM(QUANTIDADE * PREÇO) FATURAMENTO, SUM(QUANTIDADE * PREÇO)/@DENOMINADOR COMISSÃO
FROM		[ITENS NOTAS FISCAIS]	INF
INNER JOIN	[NOTAS FISCAIS]			NF
ON			INF.NUMERO = NF.NUMERO
WHERE		NF.CPF	  = '1471156710'
AND			YEAR(NF.[DATA]) = 2016


CREATE	PROCEDURE TrataErroZero
 @CPF			VARCHAR(12)
,@ANO			INT
,@DENOMINADOR	INT
,@NUMERRO		INT OUTPUT
,@NUMLINHA		INT	OUTPUT
AS
BEGIN
	SELECT		 SUM(QUANTIDADE * PREÇO) FATURAMENTO
				,SUM(QUANTIDADE * PREÇO)/@DENOMINADOR COMISSÃO
	FROM		[ITENS NOTAS FISCAIS]	INF
	INNER JOIN	[NOTAS FISCAIS]			NF
	ON			INF.NUMERO = NF.NUMERO
	WHERE		NF.CPF	  = @CPF
	AND			YEAR(NF.[DATA]) = @ANO
	SELECT		@NUMERRO = @@ERROR, @NUMLINHA = @@ROWCOUNT
END

DECLARE	@DENOMINADOR	INT
DECLARE	@CPF			VARCHAR(12)
DECLARE	@ANO			INT
DECLARE	@NUMERRO			INT
DECLARE	@NUMLINHA		INT
SET		@CPF	=	'1471156710'
SET		@ANO	=	2016
SET		@DENOMINADOR = 0
EXEC	TrataErroZero	 @CPF = @CPF
						,@ANO = @ANO
						,@DENOMINADOR = @DENOMINADOR
						,@NUMERRO = @NUMERRO OUTPUT
						,@NUMLINHA = @NUMLINHA OUTPUT
IF		@NUMERRO <> 0
	PRINT 'Houve algum erro: ' + CONVERT(VARCHAR(30), @NUMERRO) + ' - ' + CONVERT(VARCHAR(30), @NUMLINHA)


-- Tratando erro na inclusão de um vendedor

CREATE PROCEDURE	InclusaoVendedor01
 @MATRICULA		AS VARCHAR(5)
,@NOME			AS VARCHAR(100)
,@PERCENTUAL	AS FLOAT
,@DATAADMISSAO	AS DATE
,@FERIAS		AS BIT
,@BAIRRO		AS VARCHAR(50)
,@NUMERRO		INT OUTPUT
,@NUMLINHA		INT OUTPUT
AS
BEGIN
INSERT INTO [TABELA DE VENDEDORES]
VALUES
(
 @MATRICULA
,@NOME
,@PERCENTUAL
,@DATAADMISSAO
,@FERIAS
,@BAIRRO
)
SELECT			@NUMERRO = @@ERROR, @NUMLINHA = @@ROWCOUNT
END

DECLARE @NUMERRO		INT
DECLARE @NUMLINHA		INT
EXEC	InclusaoVendedor01 '0238', 'Pericles Alves', 0.11, '20160821', 0, 'Santo Amaro', @NUMERRO = @NUMERRO OUTPUT, @NUMLINHA = @NUMLINHA OUTPUT
IF		@NUMERRO <> 0
PRINT	'Houve algum erro: ' + CONVERT(VARCHAR(30), @NUMERRO) + ' - ' + CONVERT(VARCHAR(30), @NUMLINHA)

-- Tratamento com Try-Catch

CREATE	PROCEDURE [dbo].[TrataErroTryCatch]
 @CPF			VARCHAR(12)
,@ANO			INT
,@DENOMINADOR	INT
,@MENSAGEM		VARCHAR(50) OUTPUT
AS
BEGIN
	BEGIN	TRY
			SELECT		 SUM(QUANTIDADE * PREÇO) FATURAMENTO
						,SUM(QUANTIDADE * PREÇO)/@DENOMINADOR COMISSÃO
			FROM		[ITENS NOTAS FISCAIS]	INF
			INNER JOIN	[NOTAS FISCAIS]			NF
			ON			INF.NUMERO = NF.NUMERO
			WHERE		NF.CPF	  = @CPF
			AND			YEAR(NF.[DATA]) = @ANO
	END		TRY

	BEGIN	CATCH
		SET	@MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR (10), @@ERROR)
	END		CATCH
END

DECLARE	@DENOMINADOR INT
DECLARE	@CPF		VARCHAR(12)
DECLARE	@ANO		INT
DECLARE	@MENSAGEM	VARCHAR(30)

SET		@CPF = '1471156710'
SET		@ANO = 2016
SET		@DENOMINADOR = 0
SET		@MENSAGEM = ''

EXEC TrataErroTryCatch   @CPF = @CPF
						,@ANO = @ANO
						,@DENOMINADOR = @DENOMINADOR
						,@MENSAGEM = @MENSAGEM OUTPUT
IF						@MENSAGEM <> ''
	PRINT				@MENSAGEM

-- Tratamento com Try-Catch na inclusão de um vendedor


CREATE PROCEDURE	InclusaoVendedor02
 @MATRICULA		AS VARCHAR(5)
,@NOME			AS VARCHAR(100)
,@PERCENTUAL	AS FLOAT
,@DATAADMISSAO	AS DATE
,@FERIAS		AS BIT
,@BAIRRO		AS VARCHAR(50)
,@MENSAGEM		AS VARCHAR(30) OUTPUT
AS
BEGIN
	BEGIN	TRY
		INSERT INTO [TABELA DE VENDEDORES]
		VALUES
		(
		 @MATRICULA
		,@NOME
		,@PERCENTUAL
		,@DATAADMISSAO
		,@FERIAS
		,@BAIRRO
		)
	END		TRY

	BEGIN	CATCH
		SET @MENSAGEM = 'Houve um erro: ' + CONVERT(VARCHAR(30), @@ERROR)
	END		CATCH
END

DECLARE	@MENSAGEM	VARCHAR(30)
EXEC	InclusaoVendedor02 '0238', 'Pericles Alves', 0.11, '20160821', 0, 'Santo Amaro', @MENSAGEM = @MENSAGEM OUTPUT
IF		@MENSAGEM <> ''
PRINT	@MENSAGEM


-- Funções de erro com uso do Debug


CREATE	PROCEDURE [dbo].[TrataErroTryCatch2]
 @CPF			VARCHAR(12)
,@ANO			INT
,@DENOMINADOR	INT
,@MENSAGEM		VARCHAR(250) OUTPUT
AS
BEGIN
	BEGIN	TRY
			SELECT		 SUM(QUANTIDADE * PREÇO) FATURAMENTO
						,SUM(QUANTIDADE * PREÇO)/@DENOMINADOR COMISSÃO
			FROM		[ITENS NOTAS FISCAIS]	INF
			INNER JOIN	[NOTAS FISCAIS]			NF
			ON			INF.NUMERO = NF.NUMERO
			WHERE		NF.CPF	  = @CPF
			AND			YEAR(NF.[DATA]) = @ANO
	END		TRY

	BEGIN	CATCH
		SET	@MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(10), ERROR_NUMBER()) + ' - ' 
		SET	@MENSAGEM = @MENSAGEM + 'Mensagem: ' + ERROR_MESSAGE() + ' - ' 
		SET	@MENSAGEM = @MENSAGEM + 'Grau de severidade do erro: ' + CONVERT(VARCHAR(10), ERROR_SEVERITY()) + ' - ' 
		SET	@MENSAGEM = @MENSAGEM + 'Estado do erro: ' + CONVERT(VARCHAR(10), ERROR_STATE()) + ' - ' 
		SET	@MENSAGEM = @MENSAGEM + 'Estado do erro: ' + CONVERT(VARCHAR(10), ERROR_STATE()) + ' - ' 
		SET	@MENSAGEM = @MENSAGEM + 'Número da linha do erro: ' + CONVERT(VARCHAR(10), ERROR_LINE()) + ' - '
		SET	@MENSAGEM = @MENSAGEM + 'Procedure: ' + ERROR_PROCEDURE()
	END		CATCH
END

DECLARE		@DENOMINADOR INT
DECLARE		@CPF		 VARCHAR(12)
DECLARE		@ANO		 INT
DECLARE		@MENSAGEM	 VARCHAR(MAX)

SET			@DENOMINADOR = 0
SET			@CPF = '1471156710'
SET			@ANO = 2016
SET			@MENSAGEM = ''
EXEC		TrataErroTryCatch2   @CPF = @CPF
								,@ANO = @ANO
								,@DENOMINADOR = @DENOMINADOR
								,@MENSAGEM = @MENSAGEM OUTPUT
IF			@MENSAGEM <> ''
PRINT		@MENSAGEM
